name: Run Test Classes

on:
  push:
    paths:
    #  - force-app/**
  workflow_dispatch:  

jobs:
  run-test-classes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SFDX
        run: |
          npm install @salesforce/cli --global
          sf version
      - name: Login To Org
        run: |
          sf org login sfdx-url -f <(echo "${{ secrets.SFDX_AUTH_URL_IDPEACE }}") -s
      - name : Find Target Org
        run: |
          sf org list
      - name: Run Test Classes
        run: |
          sf apex run test -l RunLocalTests -w 15
      - name: Run validation
        run: |
          sf project deploy validate --source-dir force-app   