name: Run Test Classes

on:
  #push:
  #  branches:
  #    - master
  #  paths:
  #    - force-app/**
  workflow_dispatch:
    inputs:
      Apexclasses:
        description: 'Comma-separated Apex classes to deploy'
        required: true
        default: 'MyClass1,MyClass2'
      Apextests:
        description: 'Comma-separated test classes to run'
        required: true
        default: 'MyClass1Test,MyClass2Test'  

jobs:
  run-test-classes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SFDX
        run: |
          npm install @salesforce/cli --global
          sf version
      - name: Login To Org
        run: |
          sf org login sfdx-url -f <(echo "${{ secrets.SFDX_AUTH_URL_IDPEACE }}") -s
      - name : Find Target Org
        run: |
          sf org list
      #- name: Run Test Classes
      #  run: |
      #    sf apex run test -l RunLocalTests -w 15
      #- name: Run validation
      #  run: |
      #    sf project deploy validate --manifest manifest/package.xml
      - name: Deploy Selected Classes
        run: |
          echo "Deploying Apexclasses: ${{ github.event.inputs.Apexclasses }}"
          echo "Running Apextests: ${{ github.event.inputs.Apextests }}"
          sf project deploy validate
            --metadata ApexClass:${{ github.event.inputs.Apexclasses }} \
            --testlevel RunSpecifiedTests \
            --runtests ${{ github.event.inputs.Apextests }}